server:
  port: 8080

spring:
  application:
    name: ecommerce-api
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    org.springframework.security: DEBUG
    com.ecommerce: DEBUG

jwt:
  secret: mySecretKey1234567890123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000

app:
  jwtSecret: mySecretKey1234567890123456789012345678901234567890123456789012345678901234567890
  jwtExpirationInMs: 86400000
